# Generated by Django 3.2.5 on 2021-07-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(default=200, verbose_name='height in px')),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('link_flag', models.BooleanField(default=False)),
                ('expired_link_flag', models.BooleanField(default=False)),
                ('size', models.ManyToManyField(related_name='sizes', to='tiers.Size')),
            ],
        ),
    ]
