# Generated by Django 3.2.5 on 2021-07-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='expired_link_flag',
            field=models.BooleanField(default=False, help_text='Can user create expiring links?', verbose_name='Expiring links'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='link_flag',
            field=models.BooleanField(default=False, help_text='Can user see link for original image?', verbose_name='Link for original image'),
        ),
    ]
